name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  SSH:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: | 
            [! -d "valorant-clone" ] && git clone -b main https://github.com/MostafaEllethy/valorant-clone.git --single-branch
            cd valorant-clone
            git fetch
            git checkout main
            git pull
            sudo docker-compose up -d --build
